import type { Metadata } from "next";
import { Providers } from "@/components/ui/provider";

export const metadata: Metadata = {
  title: "Cognivia - The AI Learning Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
